import type { Metadata } from 'next';
import ErrorBoundary from './error';
import './globals.scss';

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'admin brave weels',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      type: 'image/ico',
      sizes: '60x30',
      url: '/favicon.ico',
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ErrorBoundary>
        <body>{children}</body>
      </ErrorBoundary>
    </html>
  );
}
