import type { Metadata } from 'next';
import ErrorBoundary from '@/components/base/error-boundary/error-boundary';
import Header from '@/components/base/header/header';
import Footer from '@/components/base/footer/footer';
import StoreProvider from '../lib/StoreProvider';
import './globals.scss';

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'admin brave weels',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ErrorBoundary>
        <body>
          <StoreProvider>
            <Header />
            {children}
            <Footer />
          </StoreProvider>
        </body>
      </ErrorBoundary>
    </html>
  );
}
